
-- DROP TABLE Family;
-- DROP TABLE EmployeeSalary;
-- DROP TABLE Employee;
-- DROP TABLE Kid;
-- DROP TABLE Tutor;
-- DROP TABLE DayCareGroupMember;
-- DROP TABLE DayCareGroup;
-- DROP TABLE Person;

CREATE TABLE Employee (
  idEmployee BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  dateOfBirth DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE EmployeeSalary (
	idEmployeeSalary BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idEmployee BIGINT NOT NULL,
    hourlyRate numeric(19,4) NOT NULL,
    effectiveDate DATE NOT NULL,
    CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (idEmployee) REFERENCES Employee (idEmployee)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE Kid (
	idKid BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	dateOfBirth DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE Tutor (
	idTutor BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    dateOfBirth DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE Family (
	idKid BIGINT NOT NULL,
    idTutor BIGINT NOT NULL,
    PRIMARY KEY (idKid, idTutor),
    CONSTRAINT FK_FAMILY_KID FOREIGN KEY (idKid) REFERENCES Kid (idKid),
    CONSTRAINT FK_FAMILY_TUTOR FOREIGN KEY (idTutor) REFERENCES Tutor (idTutor)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE DayCareGroup (
	idDayCareGroup BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    groupName VARCHAR(50) NOT NULL,
    groupDescription VARCHAR(150) NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE DayCareGroupKid (
	idKid BIGINT NOT NULL,
    idDayCareGroup BIGINT NOT NULL,
    PRIMARY KEY (idKid, idDayCareGroup),
    CONSTRAINT FK_GROUPKID_Kid FOREIGN KEY (idKid) REFERENCES Kid (idKid),
    CONSTRAINT FK_GROUPMEMBER_GROUP FOREIGN KEY (idDayCareGroup) REFERENCES DayCareGroup (idDayCareGroup)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE DayCareGroupEmployee (
	idEmployee BIGINT NOT NULL,
    idDayCareGroup BIGINT NOT NULL,
    PRIMARY KEY (idEmployee, idDayCareGroup),
    CONSTRAINT FK_GROUPEMPLOYEE_EMPLOYEE FOREIGN KEY (idEmployee) REFERENCES Employee (idEmployee),
    CONSTRAINT FK_GROUPEMPLOYEE_GROUP FOREIGN KEY (idDayCareGroup) REFERENCES DayCareGroup (idDayCareGroup)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;