
#DROP TABLE Family;
#DROP TABLE EmployeeSalary;
#DROP TABLE Employee;
#DROP TABLE Kid;
#DROP TABLE Tutor;
#DROP TABLE DayCareGroupMember;
#DROP TABLE DayCareGroup;
#DROP TABLE Person;

CREATE TABLE Person (
  idPerson BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  dateOfBirth DATE NOT NULL,
  registrationDate DATETIME NOT NULL,
  updatedDate DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE Employee (
  idEmployee BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  idPerson BIGINT NOT NULL,
  employmentDate DATE NOT NULL,
  CONSTRAINT FK_EMPLOYEE_PERSON FOREIGN KEY (idPerson) REFERENCES Person (idPerson)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE EmployeeSalary (
	idEmployeeSalary BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idEmployee BIGINT NOT NULL,
    hourlyRate numeric(19,4) NOT NULL,
    effectiveDate DATE NOT NULL,
    CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (idEmployee) REFERENCES Employee (idEmployee)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE Kid (
	idKid BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idPerson BIGINT NOT NULL,
    CONSTRAINT FK_KID_PERSON FOREIGN KEY (idPerson) REFERENCES Person (idPerson)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE Tutor (
	idTutor BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idPerson BIGINT NOT NULL,
    CONSTRAINT FK_TUTOR_PERSON FOREIGN KEY (idPerson) REFERENCES Person (idPerson)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE Family (
	
	idKid BIGINT NOT NULL,
    idTutor BIGINT NOT NULL,
    PRIMARY KEY (idKid, idTutor),
    CONSTRAINT FK_FAMILY_KID FOREIGN KEY (idKid) REFERENCES Kid (idKid),
    CONSTRAINT FK_FAMILY_TUTOR FOREIGN KEY (idTutor) REFERENCES Tutor (idTutor)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE DayCareGroup (
	idDayCareGroup BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    groupName VARCHAR(50) NOT NULL,
    groupDescription VARCHAR(150) NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE DayCareGroupMember (
	idPerson BIGINT NOT NULL,
    idDayCareGroup BIGINT NOT NULL,
    PRIMARY KEY (idPerson, idDayCareGroup),
    CONSTRAINT FK_GROUPMEMBER_PERSON FOREIGN KEY (idPerson) REFERENCES Person (idPerson),
    CONSTRAINT FK_GROUPMEMBER_GROUP FOREIGN KEY (idDayCareGroup) REFERENCES DayCareGroup (idDayCareGroup)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;